CREATE DATABASE IF NOT EXISTS SourceUndead;
USE SourceUndead;
CREATE TABLE IF NOT EXISTS players(
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	username VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);